name: Storybook build & deploy
on:
  push:
    branches:
      - develop
    paths:
      - 'package.json'
      - 'src/**'
      - 'config/**'
      - '.github/workflows/**'

jobs:
  build:
    name: Main Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup the environment
        run: |
          git config user.name "Husam Ibrahim"
          git config user.email "huielbashir@gmail.com"
          yarn

      - name: Build storybook
        run: yarn storybook:build

      - name: Deploy storybook
        run: |
          git pull
          git checkout gh-pages
          git add storybook-static
          git stash
          rm -rf ./**
          git add .
          git commit -m 'automated: new storybook deployment'
          git stash pop
          git mv storybook-static/* ./
          git commit --amend --no-edit
          git push
